[package]
name = "gedent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.0", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
confy = "0.5.1"
serde = "1.0.152"
serde_derive = "1.0.152"
wild = "2.1.0"
