[gedent]
default_extension = "inp"

[parameters]
charge = 1
basis_set = "def2svp"
functional = "BP86"
functional_class = "GGA" #required by adf
memory = 3000
mult = 1
nprocs = 8
solvation = false
solvent = "water"
split_index = 10
start_hessian = false
