[gedent]
default_extension = "inp"

[parameters]
basis_set = "def2svp"
charge = 1
method = "BP86"
method_class = "GGA"
mem = 3000
mult = 1
nprocs = 20
solvation = false
solvent = "water"
split_index = 10
hessian = false
solvation_model = "CPCM"
dispersion = "D3"
