[gedent]
default_extension = "inp"

[parameters]
charge = 1
dft_basis_set = "def2svp"
dft_level = "PB86"
dft_type = "GGA"
memory = 3000
mult = 1
nprocs = 8
solvation = false
solvent = "water"
split_index = 10
start_hessian = true
xyz_file = "init.xyz"
