[gedent]
default_extension = "inp"

[parameters]
basis_set = "def2svp"
charge = 1
functional = "BP86"
functional_class = "GGA"
memory = 3000
mult = 1
nprocs = 8
solvent = "dmso"
split_index = 10
start_hessian = false
