[gedent]
default_extension = "inp"
default_nr_files = 1

[parameters]
charge = 1
dft_basis_set = "def2svp"
dft_level = "PB86"
memory = 3000
mult = 1
nprocs = 8
solvation = false
solvent = "water"
xyz_file = "init.xyz"
