[gedent]
default_extension = "inp"

[parameters]
basis_set = "def2svp"
charge = 1
functional = "BP86"
functional_class = "GGA"
memory = 3000
multiplicity = 1
nprocs = 20
solvation = false
solvent = "water"
split_index = 10
hessian = false
