[gedent]
default_extension = "inp"

[model]
method = "BP86"
basis_set = "def2svp"
charge = 0
mult = 1
dispersion = "D3"
solvent = "water"
solvation_model = "CPCM"

[resources]
nprocs = 20
mem = 3000

[parameters]
method_class = "GGA"
